name: "Create release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose --all

  create-release:
    runs-on: ubuntu-latest
    needs: [run-tests]
    outputs:
      upload_url: ${{ steps.create-release-step.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        id: create-release-step
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          files: |
            LICENSE

  build-releases:
    runs-on: ${{ matrix.os }}
    needs: [create-release]
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos_arm]
        include:
          - os: windows-latest
            extension: .exe
            name: windows
          - os: ubuntu-latest
            extension: ''
            name: linux
          - os: macos-latest
            extension: ''
            name: macos_x86

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build For Target
        run: cargo build --release --verbose
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/release/vfpl${{ matrix.extension }}
          asset_name: vfpl_${{ matrix.name }}${{ matrix.extension }}